# Generated by Django 5.2.3 on 2025-06-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("DF", "Draft"), ("PB", "published")],
                default="DF",
                max_length=2,
            ),
        ),
    ]
